spring :
  profiles:
    active: dev

mybatis:
      configuration:
          map-underscore-to-camel-case: true
      mapper-locations: mappers/*Mapper.xml
      type-aliases-package: kr.co.rland.web.entity